### ISSUE TITLE
Po uruchomieniu wyskakuje mi błąd:

### ISSUE THREAD

**Issue by KacperK4** [kotekpsotek/awesome-instaling#2]
Traceback (most recent call last):
  File "C:\Users\kacpe\Downloads\awesome-instaling-master\main.py", line 10, in <module>
    main()
  File "C:\Users\kacpe\Downloads\awesome-instaling-master\main.py", line 6, in main
    start_instaling(login, password) # start instaling
  File "C:\Users\kacpe\Downloads\awesome-instaling-master\instaling.py", line 564, in start_instaling
    browser = webdriver.Chrome(service = Service(executable_path=webdriver_path), options = chrome_options)
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    super().__init__(
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 107
Current browser version is 105.0.5195.127 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00B48CE3+2067683]
        Ordinal0 [0x00ADCBC1+1625025]
        Ordinal0 [0x009DB7CD+571341]
        Ordinal0 [0x009FDFED+712685]
        Ordinal0 [0x009F9286+692870]
        Ordinal0 [0x009F6BF9+683001]
        Ordinal0 [0x00A2DBF6+908278]
        Ordinal0 [0x00A2D6CA+906954]
        Ordinal0 [0x00A27156+880982]
        Ordinal0 [0x009FFF1D+720669]
        Ordinal0 [0x00A00F5F+724831]
        GetHandleVerifier [0x00DFF162+2771330]
        GetHandleVerifier [0x00DF1145+2713957]
        GetHandleVerifier [0x00BDCC0A+533546]
        GetHandleVerifier [0x00BDB970+528784]
        Ordinal0 [0x00AE4F4C+1658700]
        Ordinal0 [0x00AE98B8+1677496]
        Ordinal0 [0x00AE99A5+1677733]
        Ordinal0 [0x00AF4CC4+1723588]
        BaseThreadInitThunk [0x76197BA9+25]
        RtlInitializeExceptionChain [0x7705BB3B+107]
        RtlClearBits [0x7705BABF+191]

**Comment by kotekpsotek** [comment]
Welcome @KacperK4. You should try to update webdriver for Chrome browswer located in [this](https://github.com/kotekpsotek/awesome-instaling/tree/master/webdriver_path) folder to the version appropriate for your actual browswer version. Available drivers for chrome are under [link]https://chromedriver.chromium.org/downloads. Thanks for issue and please attach feedback about whether that helps in your case 😘

**Comment by KacperK4** [comment]
Next problem wtih googletrans module:

Page is loading...
Page is loaded!!! -> Start loging
You have been signed in!!!
Traceback (most recent call last):
  File "c:\Users\kacpe\Desktop\awesome-instaling-master\main.py", line 10, in <module>
  File "c:\Users\kacpe\Desktop\awesome-instaling-master\instaling.py", line 429, in translate_this_word
    local_translation = translate_word_by_use_google_tr(word_to_translate).text
  File "c:\Users\kacpe\Desktop\awesome-instaling-master\instaling.py", line 323, in translate_word_by_use_google_tr
    translator_word_lang_detect = translator_machine.detect(word).lang
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 255, in detect
    data = self._translate(text, 'en', 'auto', kwargs)
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
PS C:\Users\kacpe\Desktop\awesome-instaling-master>
