### ISSUE TITLE
googletrans Module Error

### ISSUE THREAD

**Issue by KacperK4** [kotekpsotek/awesome-instaling#4]
@kotekpsotek Next problem wtih googletrans module:

Page is loading...
Page is loaded!!! -> Start loging
You have been signed in!!!
Traceback (most recent call last):
File "c:\Users\kacpe\Desktop\awesome-instaling-master\main.py", line 10, in
File "c:\Users\kacpe\Desktop\awesome-instaling-master\instaling.py", line 429, in translate_this_word
local_translation = translate_word_by_use_google_tr(word_to_translate).text
File "c:\Users\kacpe\Desktop\awesome-instaling-master\instaling.py", line 323, in translate_word_by_use_google_tr
translator_word_lang_detect = translator_machine.detect(word).lang
File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 255, in detect
data = self._translate(text, 'en', 'auto', kwargs)
File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\client.py", line 78, in _translate
token = self.token_acquirer.do(text)
File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\gtoken.py", line 194, in do
self._update()
File "C:\Users\kacpe\AppData\Local\Programs\Python\Python310\lib\site-packages\googletrans\gtoken.py", line 62, in _update
code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by kotekpsotek** [comment]
Your error as you said <b>is caused by googletrans module</b>, but more accuratly by changes in ***Google Translator API*** that aren't covered by your version of that module. To solve that case you must change your **googletrans module** verision to "that correct" by re-install it. Firstly let try every from this versions batch: **3.1.0a0**, **4.0.0-rc1**, **1.8.9** (one of them should solve your problem). When your problem still exists, try to pull issue on [googlegrans official github repository](https://github.com/ssut/py-googletrans). You can also use version from [release](https://github.com/kotekpsotek/awesome-instaling/releases) which is compiled using correct version (for that moment),

**Comment by KacperK4** [comment]
@kotekpsotek i can't find other version whan 1.2 or 2.4.0. Can you send me link where i can download older versions?

This versions not work.

![image](https://user-images.githubusercontent.com/102327280/203653539-79202353-fc3b-44f7-b166-cfd9a63fd715.png)

**Comment by kotekpsotek** [comment]
You must perform that using PyPI package manager. Please apply to this form: **pip -Iv install googletrans==version**. Full list of googletrans releases is there: https://pypi.org/project/googletrans/#history (copy one from versions and replace **version** to it)

**Comment by KacperK4** [comment]
@kotekpsotek Ok it works but the bot cant type capital letters:
bot type "tisch"
correct "Tisch"

how to fix it?
